name: deploy to staging server
on:
  workflow_dispatch:
  workflow_call:
jobs:
  deploy-to-staging-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install CloudFlared      
        run: |          
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          sudo apt install curl
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null          
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install cloudflared -y      
      
      - name: Scan and Trust Server Fingerprint
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOSTNAME }} \
          --proxy "cloudflared access tcp --hostname %h" >> ~/.ssh/known_hosts
          
      - name: Configure SSH for Cloudflare Tunnel
        run: |
          mkdir -p ~/.ssh
          echo "Host ${{ secrets.HOSTNAME }}" >> ~/.ssh/config
          echo "    ProxyCommand /usr/local/bin/cloudflared access tcp --hostname %h" >> ~/.ssh/config

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Staging
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} << EOF
          cd /var/www/html/
          sudo mv improved-octo-disco-feature ${{ github.run_number }}
          cd /tmp/
          git clone https://github.com/cinnamon17/improved-octo-disco.git
          mv improved-octo-disco/ improved-octo-disco-feature
          cd improved-octo-disco-feature
          git checkout staging
          echo APP_ENV=${{ secrets.APP_ENV }} >.env
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} >> .env
          echo BOT_KEY=${{ secrets.BOT_KEY_STAGING }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_STAGING }} >> .env
          echo MESSENGER_TRANSPORT_DSN='${{ secrets.BUS_DSN }}' >> .env
          echo DEFAULT_URI='${{ secrets.DEFAULT_URI }}' >> .env
          composer install
          composer dump-env prod
          php bin/console messenger:stop-workers
          php bin/console doctrine:migrations:migrate -n
          cd ..
          sudo mv improved-octo-disco-feature/ /var/www/html/
          cd /var/www/html
          ./permits.sh
          EOF
