name: deploy to staging server
on:
  workflow_dispatch:
          #push:
          #branches:
          #- staging
jobs:
  deploy-to-staging-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          debug: true

      - name: Deploy to Staging
        run: |
          remote_server="${{ secrets.HOSTNAME }}"
          remote_user="${{ secrets.USER }}"

          ssh $remote_user@$remote_server "pwd"
