name: deploy to staging server
on:
  workflow_dispatch:
          #push:
          #branches:
          #- staging
jobs:
  deploy-to-staging-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOSTNAME }} << EOF
          cd /var/www/html/staging
          mv symfony-api ${{ github.run_number }}
          git clone https://github.com/cinnamon17/symfony-api.git
          cd symfony-api
          git checkout staging
          echo APP_ENV=${{ secrets.APP_ENV }} >.env
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} >> .env
          echo BOT_KEY=${{ secrets.BOT_KEY_STAGING }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_STAGING }} >> .env
          composer install
          composer dump-env prod
          php bin/console doctrine:migrations:migrate -n
          HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1)
          sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX var
          sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX var

          EOF
